version: "3.3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - clarity
    ports:
      - 2181:2181

  clarity-kafka:
    image: bitnami/kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://clarity-kafka:9092

    volumes:
      - kafka:/bitnami/kafka:cached
    ports:
      - "9092:9092"
    networks:
      - clarity
    restart: always
    depends_on:
      - zookeeper

  clarity-client-go:
    image: ethereum/client-go
    volumes:
      - ethereum:/root:cached
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    command: "--rpc --rpcaddr '0.0.0.0' --rpcport '8545' --ws --wsaddr '0.0.0.0' --wsport '8546' --syncmode 'light' --rinkeby"
    restart: always
    networks:
      - clarity
volumes:
  kafka:
  ethereum:

  # node_modules:
networks:
  clarity:
    driver: bridge
