micronaut:
  application:
    name: clarity-hyperledger

  server:
    port: 8889

#  security:
#    enabled: true
#    endpoints:
#      login:
#        enabled: true
#      oauth:
#        enabled: true
#    token:
#      jwt:
#        enabled: true
#        signatures:
#          secret:
#            generator:
#              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
tracing:
  zipkin:
    enabled: true
    http:
      url: http://clarity-hyperledger:9411
    sampler:
      probability: 0.1

#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#jpa:
#  default:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#eureka:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
#mongodb:
#  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
kafka:
  bootstrap:
    servers: clarity-kafka:9092
